### ISSUE TITLE
Monster assets

### ISSUE THREAD

**Issue by Lm48HC** [Vertylo/wakassets#2]
Hey, first of all, just wanted to say thanks for sharing the assets, because I've been looking for a while and can't figure out how to extract the game assets myself.
Could you please make a folder for the monster assets (the actual textures, not their combat cards like in the monster folder)? If not, could you explain how it's done so that I may do it myself? Thank you.

**Comment by Vertylo** [comment]
https://github.com/killmeiambot/Wakfu-tgam
